# Copyright (c) 2024-2026 LabelCraft
# YOLO-Pose annotation reader / writer (Ultralytics format)

"""
YOLO-Pose label line:
  cls cx cy w h  kx1 ky1 v1  kx2 ky2 v2 ... kxK kyK vK
All coordinates normalized to [0, 1]. Visibility v in {0, 1, 2}.
"""

from __future__ import annotations

import os
from typing import Any, Dict, List, Optional, Sequence, Tuple

TXT_EXT = '.txt'


def is_pose_label_line(parts: Sequence[str], kpt_dim: int = 3) -> bool:
    """True if token count looks like detect(5) + K*kpt_dim keypoints."""
    n = len(parts)
    if n <= 5:
        return False
    return (n - 5) % kpt_dim == 0 and (n - 5) // kpt_dim >= 1


def peek_kpt_count(txt_path: str, kpt_dim: int = 3) -> Optional[int]:
    """Infer keypoint count K from the first valid pose line, or None."""
    if not os.path.isfile(txt_path):
        return None
    with open(txt_path, 'r', encoding='utf-8') as f:
        for line in f:
            parts = line.strip().split()
            if is_pose_label_line(parts, kpt_dim):
                return (len(parts) - 5) // kpt_dim
    return None


def file_looks_like_pose(txt_path: str) -> bool:
    return peek_kpt_count(txt_path) is not None


def parse_data_yaml(yaml_path: str) -> Dict[str, Any]:
    """
    Parse Ultralytics data.yaml for pose datasets.
    Returns dict with keys: names, nc, kpt_shape, flip_idx, skeleton, paths...
    """
    result: Dict[str, Any] = {
        'names': [],
        'nc': 0,
        'kpt_shape': None,
        'flip_idx': None,
        'skeleton': None,
        'train': None,
        'val': None,
        'test': None,
        'yaml_path': yaml_path,
    }
    if not yaml_path or not os.path.isfile(yaml_path):
        return result

    try:
        import yaml
    except ImportError:
        print('Warning: PyYAML not installed; cannot parse data.yaml for pose.')
        return result

    with open(yaml_path, 'r', encoding='utf-8') as f:
        data = yaml.safe_load(f) or {}

    names = data.get('names', [])
    if isinstance(names, dict):
        names = [str(names[k]).strip() for k in sorted(names.keys()) if names[k]]
    elif isinstance(names, list):
        names = [str(n).strip() for n in names if n]
    else:
        names = []

    result['names'] = names
    result['nc'] = int(data.get('nc', len(names) or 0))
    if data.get('kpt_shape'):
        result['kpt_shape'] = list(data['kpt_shape'])
    if data.get('flip_idx') is not None:
        result['flip_idx'] = list(data['flip_idx'])
    if data.get('skeleton') is not None:
        result['skeleton'] = [list(edge) for edge in data['skeleton']]
    for key in ('train', 'val', 'test'):
        if key in data:
            result[key] = data[key]
    return result


def find_data_yaml(start_dir: str) -> Optional[str]:
    """Search common locations for data.yaml near a labels/images folder."""
    candidates = [
        os.path.join(start_dir, 'data.yaml'),
        os.path.join(os.path.dirname(start_dir), 'data.yaml'),
        os.path.join(os.path.dirname(os.path.dirname(start_dir)), 'data.yaml'),
    ]
    for path in candidates:
        if os.path.isfile(path):
            return path
    return None


def write_data_yaml(
    output_path: str,
    names: Sequence[str],
    kpt_shape: Sequence[int],
    flip_idx: Optional[Sequence[int]] = None,
    skeleton: Optional[Sequence[Sequence[int]]] = None,
    train: str = 'train/images',
    val: str = 'valid/images',
    test: Optional[str] = 'test/images',
) -> str:
    """Write Ultralytics YOLO-Pose data.yaml (comments included)."""
    if flip_idx is None:
        flip_idx = list(range(int(kpt_shape[0])))

    lines = [
        '# YOLO-Pose dataset config (generated by LabelCraft)',
        '# Usage: yolo pose train data=data.yaml model=yolo11n-pose.pt imgsz=640',
        '',
        f'train: {train}',
        f'val: {val}',
    ]
    if test:
        lines.append(f'test: {test}')
    lines.extend([
        '',
        f'kpt_shape: [{int(kpt_shape[0])}, {int(kpt_shape[1])}]',
        f'flip_idx: [{", ".join(str(int(i)) for i in flip_idx)}]',
    ])
    if skeleton:
        sk = ', '.join('[' + ', '.join(str(int(i)) for i in edge) + ']' for edge in skeleton)
        lines.append(f'skeleton: [{sk}]')
    lines.extend([
        '',
        f'nc: {len(names)}',
        'names: [' + ', '.join(repr(n) for n in names) + ']',
        '',
    ])

    os.makedirs(os.path.dirname(os.path.abspath(output_path)) or '.', exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    return output_path


class YOLOPoseWriter:
    """Write a single-image YOLO-Pose label file."""

    def __init__(self, img_size: Sequence[int], class_list: Optional[List[str]] = None,
                 kpt_shape: Sequence[int] = (3, 3)):
        """
        Args:
            img_size: [height, width, ...] (same convention as YOLOWriter)
            class_list: ordered class names
            kpt_shape: [K, dim] where dim is usually 3
        """
        self.img_h = int(img_size[0])
        self.img_w = int(img_size[1])
        self.class_list = list(class_list or [])
        self.kpt_count = int(kpt_shape[0])
        self.kpt_dim = int(kpt_shape[1]) if len(kpt_shape) > 1 else 3
        self.box_list: List[Dict[str, Any]] = []
        self.verified = False

    def add_pose(
        self,
        xmin: float,
        ymin: float,
        xmax: float,
        ymax: float,
        label: str,
        keypoints: Sequence[Any],
        difficult: int = 0,
    ):
        """
        keypoints: list of (x, y, v) or dict {'x','y','v'} in **pixel** coordinates.
        Missing keypoints are padded as (0, 0, 0).
        """
        kpts = []
        for i in range(self.kpt_count):
            if i < len(keypoints):
                kp = keypoints[i]
                if isinstance(kp, dict):
                    x, y, v = float(kp.get('x', 0)), float(kp.get('y', 0)), int(kp.get('v', 0))
                else:
                    x = float(kp[0])
                    y = float(kp[1])
                    v = int(kp[2]) if len(kp) > 2 else 2
            else:
                x, y, v = 0.0, 0.0, 0
            kpts.append((x, y, v))

        self.box_list.append({
            'xmin': float(xmin),
            'ymin': float(ymin),
            'xmax': float(xmax),
            'ymax': float(ymax),
            'name': label,
            'difficult': difficult,
            'keypoints': kpts,
        })

    def _ensure_class(self, name: str) -> int:
        if name not in self.class_list:
            self.class_list.append(name)
        return self.class_list.index(name)

    def format_line(self, box: Dict[str, Any]) -> str:
        cls_id = self._ensure_class(box['name'])
        cx = ((box['xmin'] + box['xmax']) / 2.0) / self.img_w
        cy = ((box['ymin'] + box['ymax']) / 2.0) / self.img_h
        w = (box['xmax'] - box['xmin']) / self.img_w
        h = (box['ymax'] - box['ymin']) / self.img_h
        parts = [str(cls_id), f'{cx:.6f}', f'{cy:.6f}', f'{w:.6f}', f'{h:.6f}']
        for x, y, v in box['keypoints']:
            if self.kpt_dim >= 3:
                parts.extend([f'{x / self.img_w:.6f}', f'{y / self.img_h:.6f}', str(int(v))])
            else:
                parts.extend([f'{x / self.img_w:.6f}', f'{y / self.img_h:.6f}'])
        return ' '.join(parts)

    def save(self, target_file: str, class_list: Optional[List[str]] = None) -> str:
        if class_list is not None:
            self.class_list = list(class_list)
        if not target_file.lower().endswith(TXT_EXT):
            target_file += TXT_EXT
        os.makedirs(os.path.dirname(os.path.abspath(target_file)) or '.', exist_ok=True)
        with open(target_file, 'w', encoding='utf-8') as f:
            for box in self.box_list:
                f.write(self.format_line(box) + '\n')
        return target_file


class YOLOPoseReader:
    """
    Read YOLO-Pose labels into LabelCraft shape tuples:
      (label, points[4], line_color, fill_color, difficult, keypoints, shape_type)
    keypoints are pixel (x, y, v) tuples.
    """

    def __init__(
        self,
        file_path: str,
        image,
        class_list_path: Optional[str] = None,
        class_list: Optional[List[str]] = None,
        kpt_shape: Optional[Sequence[int]] = None,
    ):
        self.shapes: List[Tuple] = []
        self.file_path = file_path
        self.verified = False
        self.img_h = image.height()
        self.img_w = image.width()
        self.kpt_count = 0
        self.kpt_dim = 3

        if kpt_shape:
            self.kpt_count = int(kpt_shape[0])
            self.kpt_dim = int(kpt_shape[1]) if len(kpt_shape) > 1 else 3

        if class_list is not None:
            self.classes = list(class_list)
        else:
            self.classes = self._load_classes(class_list_path)

        if not self.kpt_count:
            inferred = peek_kpt_count(file_path, self.kpt_dim)
            self.kpt_count = inferred or 0

        self.parse()

    def _load_classes(self, class_list_path: Optional[str]) -> List[str]:
        if class_list_path and os.path.isfile(class_list_path):
            with open(class_list_path, 'r', encoding='utf-8') as f:
                return [ln.strip() for ln in f if ln.strip()]

        anno_dir = os.path.dirname(os.path.realpath(self.file_path))
        for candidate in (
            os.path.join(os.path.dirname(anno_dir), 'classes.txt'),
            os.path.join(anno_dir, 'classes.txt'),
        ):
            if os.path.isfile(candidate):
                with open(candidate, 'r', encoding='utf-8') as f:
                    return [ln.strip() for ln in f if ln.strip()]

        yaml_path = find_data_yaml(anno_dir)
        if yaml_path:
            meta = parse_data_yaml(yaml_path)
            if meta.get('kpt_shape') and not self.kpt_count:
                self.kpt_count = int(meta['kpt_shape'][0])
                self.kpt_dim = int(meta['kpt_shape'][1]) if len(meta['kpt_shape']) > 1 else 3
            if meta.get('names'):
                return meta['names']
        return []

    def parse(self):
        with open(self.file_path, 'r', encoding='utf-8') as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) < 5:
                    continue
                cls_id = int(float(parts[0]))
                cx, cy, w, h = map(float, parts[1:5])
                label = self.classes[cls_id] if 0 <= cls_id < len(self.classes) else str(cls_id)

                x_min = max((cx - w / 2) * self.img_w, 0)
                x_max = min((cx + w / 2) * self.img_w, self.img_w)
                y_min = max((cy - h / 2) * self.img_h, 0)
                y_max = min((cy + h / 2) * self.img_h, self.img_h)
                points = [
                    (x_min, y_min),
                    (x_max, y_min),
                    (x_max, y_max),
                    (x_min, y_max),
                ]

                keypoints = []
                rest = parts[5:]
                if rest and self.kpt_dim > 0:
                    k = self.kpt_count or (len(rest) // self.kpt_dim)
                    for i in range(k):
                        base = i * self.kpt_dim
                        if base + 1 >= len(rest):
                            keypoints.append((0.0, 0.0, 0))
                            continue
                        kx = float(rest[base]) * self.img_w
                        ky = float(rest[base + 1]) * self.img_h
                        kv = int(float(rest[base + 2])) if self.kpt_dim >= 3 and base + 2 < len(rest) else 2
                        keypoints.append((kx, ky, kv))

                shape_type = 'pose' if keypoints else 'rectangle'
                self.shapes.append((label, points, None, None, False, keypoints, shape_type))

    def get_shapes(self):
        return self.shapes


def annotations_to_pose_txt(
    annotations: Sequence[Dict[str, Any]],
    img_w: int,
    img_h: int,
    class_list: Sequence[str],
    kpt_shape: Sequence[int],
    output_path: str,
) -> bool:
    """
    Write annotations (internal converter style) to a YOLO-Pose txt.
    Each ann may include:
      label, bbox=[x,y,w,h] (xywh abs) OR bbox=[xmin,ymin,xmax,ymax],
      keypoints=[[x,y,v], ...] in pixels
    """
    writer = YOLOPoseWriter([img_h, img_w], class_list=list(class_list), kpt_shape=kpt_shape)
    wrote = False
    for ann in annotations:
        label = ann.get('label', '')
        if ann.get('bbox_xyxy'):
            xmin, ymin, xmax, ymax = ann['bbox_xyxy']
        else:
            bbox = ann.get('bbox')
            if not bbox or len(bbox) < 4:
                continue
            # Default internal converter format: x, y, w, h
            xmin, ymin, xmax, ymax = bbox[0], bbox[1], bbox[0] + bbox[2], bbox[1] + bbox[3]

        kpts = ann.get('keypoints') or []
        writer.add_pose(xmin, ymin, xmax, ymax, label, kpts)
        wrote = True
    if wrote:
        writer.save(output_path, class_list=list(class_list))
    return wrote


def export_yolo_pose_dataset(
    items: Sequence[Dict[str, Any]],
    output_dir: str,
    class_list: Sequence[str],
    kpt_shape: Sequence[int],
    flip_idx: Optional[Sequence[int]] = None,
    skeleton: Optional[Sequence[Sequence[int]]] = None,
    split: str = 'train',
    copy_images: bool = True,
) -> str:
    """
    Export a flat list of items into YOLO-Pose layout under output_dir/split/.

    Each item:
      {
        'image_path': str,
        'annotations': [ {label, bbox_xyxy=[xmin,ymin,xmax,ymax], keypoints:[[x,y,v],...]}, ... ]
      }
    """
    import shutil

    images_dir = os.path.join(output_dir, split, 'images')
    labels_dir = os.path.join(output_dir, split, 'labels')
    os.makedirs(images_dir, exist_ok=True)
    os.makedirs(labels_dir, exist_ok=True)

    for item in items:
        image_path = item['image_path']
        if not os.path.isfile(image_path):
            continue
        base = os.path.splitext(os.path.basename(image_path))[0]
        ext = os.path.splitext(image_path)[1]
        dst_img = os.path.join(images_dir, base + ext)
        if copy_images:
            shutil.copy2(image_path, dst_img)

        from PySide6.QtGui import QImage
        img = QImage(image_path)
        writer = YOLOPoseWriter(
            [img.height(), img.width()],
            class_list=list(class_list),
            kpt_shape=kpt_shape,
        )
        for ann in item.get('annotations', []):
            if 'bbox_xyxy' in ann:
                xmin, ymin, xmax, ymax = ann['bbox_xyxy']
            else:
                x, y, w, h = ann['bbox']
                xmin, ymin, xmax, ymax = x, y, x + w, y + h
            writer.add_pose(xmin, ymin, xmax, ymax, ann['label'], ann.get('keypoints') or [])
        writer.save(os.path.join(labels_dir, base + TXT_EXT), class_list=list(class_list))

    yaml_path = os.path.join(output_dir, 'data.yaml')
    # Only write yaml if train split (or always overwrite with current splits present)
    train = 'train/images' if os.path.isdir(os.path.join(output_dir, 'train', 'images')) else f'{split}/images'
    val = 'valid/images' if os.path.isdir(os.path.join(output_dir, 'valid', 'images')) else (
        'val/images' if os.path.isdir(os.path.join(output_dir, 'val', 'images')) else train
    )
    test = 'test/images' if os.path.isdir(os.path.join(output_dir, 'test', 'images')) else None
    write_data_yaml(
        yaml_path,
        names=class_list,
        kpt_shape=kpt_shape,
        flip_idx=flip_idx,
        skeleton=skeleton,
        train=train,
        val=val,
        test=test,
    )
    return yaml_path
