# Copyright (c) 2024-2026 LabelCraft
# YOLO-Seg annotation writer (Ultralytics format)

"""
YOLO-Seg label line:
  cls  x1 y1  x2 y2  ... xn yn
All coordinates normalized to [0, 1].
"""

from __future__ import annotations

import math
import os
from typing import Any, Dict, List, Optional, Sequence, Tuple

TXT_EXT = '.txt'


def write_data_yaml(
    output_path: str,
    names: Sequence[str],
    train: str = 'train/images',
    val: str = 'valid/images',
    test: Optional[str] = 'test/images',
) -> str:
    """Write Ultralytics YOLO-Seg data.yaml."""
    lines = [
        '# YOLO-Seg dataset config (generated by LabelCraft)',
        '# Usage: yolo segment train data=data.yaml model=yolo11n-seg.pt imgsz=640',
        '',
        f'train: {train}',
        f'val: {val}',
    ]
    if test:
        lines.append(f'test: {test}')
    lines.extend([
        '',
        f'nc: {len(names)}',
        'names: [' + ', '.join(repr(n) for n in names) + ']',
        '',
    ])
    os.makedirs(os.path.dirname(os.path.abspath(output_path)) or '.', exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    return output_path


def ellipse_polygon_from_points(
    points: Sequence[Sequence[float]],
    n: int = 32,
    force_circle: bool = False,
) -> List[Tuple[float, float]]:
    """Approximate an ellipse/circle AABB (from corner points) as a polygon."""
    xs = [float(p[0]) for p in points]
    ys = [float(p[1]) for p in points]
    xmin, xmax = min(xs), max(xs)
    ymin, ymax = min(ys), max(ys)
    cx, cy = (xmin + xmax) / 2.0, (ymin + ymax) / 2.0
    rx, ry = max(0.5, (xmax - xmin) / 2.0), max(0.5, (ymax - ymin) / 2.0)
    if force_circle:
        r = max(rx, ry)
        rx = ry = r
    out = []
    for i in range(n):
        a = 2.0 * math.pi * i / n
        out.append((cx + rx * math.cos(a), cy + ry * math.sin(a)))
    return out


def seg_points_from_ann(ann: Dict[str, Any]) -> Optional[List[Tuple[float, float]]]:
    """
    Extract a segmentation polygon (pixel coords) from an annotation.

    Supported:
      - polygon (>=3 points)
      - obb (4 corners)
      - ellipse / circle (approximated)
    Rectangle / pose without polygon are skipped.
    """
    ann_type = (ann.get('type') or '').lower()
    points = ann.get('points') or []
    if ann_type == 'polygon' and len(points) >= 3:
        return [(float(p[0]), float(p[1])) for p in points]
    if ann_type == 'obb' and len(points) >= 4:
        return [(float(p[0]), float(p[1])) for p in points[:4]]
    if ann_type in ('ellipse', 'circle') and len(points) >= 2:
        return ellipse_polygon_from_points(
            points, n=32, force_circle=(ann_type == 'circle'))
    return None


class YOLOSegWriter:
    """Write a single-image YOLO-Seg label file."""

    def __init__(self, img_size: Sequence[int], class_list: Optional[List[str]] = None):
        self.img_h = int(img_size[0])
        self.img_w = int(img_size[1])
        self.class_list = list(class_list or [])
        self.poly_list: List[Dict[str, Any]] = []

    def add_polygon(self, points: Sequence[Sequence[float]], label: str):
        if len(points) < 3:
            return
        self.poly_list.append({
            'points': [(float(p[0]), float(p[1])) for p in points],
            'name': label,
        })

    def _ensure_class(self, name: str, class_list: List[str]) -> int:
        if name not in class_list:
            class_list.append(name)
        return class_list.index(name)

    def save(self, target_file: str, class_list: Optional[List[str]] = None) -> bool:
        if not self.poly_list:
            return False
        names = list(class_list if class_list is not None else self.class_list)
        w = max(1, self.img_w)
        h = max(1, self.img_h)
        lines = []
        for poly in self.poly_list:
            cls_id = self._ensure_class(poly['name'], names)
            coords = []
            for x, y in poly['points']:
                coords.append(f'{max(0.0, min(1.0, x / w)):.6f}')
                coords.append(f'{max(0.0, min(1.0, y / h)):.6f}')
            lines.append(f'{cls_id} ' + ' '.join(coords))
        os.makedirs(os.path.dirname(os.path.abspath(target_file)) or '.', exist_ok=True)
        with open(target_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
            f.write('\n')
        self.class_list = names
        return True


def annotations_to_seg_txt(
    annotations: Sequence[Dict[str, Any]],
    img_w: int,
    img_h: int,
    class_list: Sequence[str],
    output_path: str,
) -> bool:
    writer = YOLOSegWriter([img_h, img_w], class_list=list(class_list))
    wrote = False
    for ann in annotations:
        pts = seg_points_from_ann(ann)
        if not pts:
            continue
        writer.add_polygon(pts, ann.get('label', ''))
        wrote = True
    if wrote:
        return writer.save(output_path, class_list=list(class_list))
    return False


def export_yolo_seg_dataset(
    items: Sequence[Dict[str, Any]],
    output_dir: str,
    class_list: Sequence[str],
    split: str = 'train',
    copy_images: bool = True,
) -> str:
    """
    Export items into YOLO-Seg layout under output_dir/split/.

    Each item:
      {
        'image_path': str,
        'annotations': [ {label, type, points=[[x,y],...]}, ... ]
      }
    """
    import shutil

    images_dir = os.path.join(output_dir, split, 'images')
    labels_dir = os.path.join(output_dir, split, 'labels')
    os.makedirs(images_dir, exist_ok=True)
    os.makedirs(labels_dir, exist_ok=True)

    for item in items:
        image_path = item['image_path']
        if not os.path.isfile(image_path):
            continue
        base = os.path.splitext(os.path.basename(image_path))[0]
        ext = os.path.splitext(image_path)[1]
        dst_img = os.path.join(images_dir, base + ext)
        if copy_images:
            shutil.copy2(image_path, dst_img)

        from PySide6.QtGui import QImage
        img = QImage(image_path)
        writer = YOLOSegWriter(
            [img.height(), img.width()],
            class_list=list(class_list),
        )
        for ann in item.get('annotations', []):
            pts = ann.get('points')
            if pts is None:
                pts = seg_points_from_ann(ann)
            elif len(pts) < 3:
                pts = seg_points_from_ann(ann)
            if not pts or len(pts) < 3:
                continue
            writer.add_polygon(pts, ann.get('label', ''))
        writer.save(os.path.join(labels_dir, base + TXT_EXT), class_list=list(class_list))

    yaml_path = os.path.join(output_dir, 'data.yaml')
    train = 'train/images' if os.path.isdir(os.path.join(output_dir, 'train', 'images')) else f'{split}/images'
    val = 'valid/images' if os.path.isdir(os.path.join(output_dir, 'valid', 'images')) else (
        'val/images' if os.path.isdir(os.path.join(output_dir, 'val', 'images')) else train
    )
    test = 'test/images' if os.path.isdir(os.path.join(output_dir, 'test', 'images')) else None
    write_data_yaml(yaml_path, names=class_list, train=train, val=val, test=test)
    return yaml_path
