# Copyright (c) 2024-2026 LabelCraft
# YOLO-OBB annotation reader / writer (Ultralytics format)

"""
YOLO-OBB label line:
  cls  x1 y1  x2 y2  x3 y3  x4 y4
All coordinates normalized to [0, 1] (relative to image width / height).
"""

from __future__ import annotations

import os
from typing import Any, Dict, List, Optional, Sequence, Tuple

TXT_EXT = '.txt'


def is_obb_label_line(parts: Sequence[str]) -> bool:
    """True if token count is class + 8 normalized corner coords."""
    return len(parts) == 9


def write_data_yaml(
    output_path: str,
    names: Sequence[str],
    train: str = 'train/images',
    val: str = 'valid/images',
    test: Optional[str] = 'test/images',
) -> str:
    """Write Ultralytics YOLO-OBB data.yaml."""
    lines = [
        '# YOLO-OBB dataset config (generated by LabelCraft)',
        '# Usage: yolo obb train data=data.yaml model=yolo11n-obb.pt imgsz=640',
        '',
        f'train: {train}',
        f'val: {val}',
    ]
    if test:
        lines.append(f'test: {test}')
    lines.extend([
        '',
        f'nc: {len(names)}',
        'names: [' + ', '.join(repr(n) for n in names) + ']',
        '',
    ])
    os.makedirs(os.path.dirname(os.path.abspath(output_path)) or '.', exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    return output_path


class YOLOObbWriter:
    """Write a single-image YOLO-OBB label file (4 normalized corners)."""

    def __init__(self, img_size: Sequence[int], class_list: Optional[List[str]] = None):
        """
        Args:
            img_size: [height, width, ...] (same convention as YOLOWriter)
            class_list: ordered class names
        """
        self.img_h = int(img_size[0])
        self.img_w = int(img_size[1])
        self.class_list = list(class_list or [])
        self.box_list: List[Dict[str, Any]] = []

    def add_obb(
        self,
        points: Sequence[Sequence[float]],
        label: str,
        difficult: int = 0,
    ):
        """points: 4 corners in pixel coords [[x,y], ...] (order preserved)."""
        if len(points) < 4:
            return
        corners = [(float(p[0]), float(p[1])) for p in points[:4]]
        self.box_list.append({
            'points': corners,
            'name': label,
            'difficult': int(difficult),
        })

    def _ensure_class(self, name: str, class_list: List[str]) -> int:
        if name not in class_list:
            class_list.append(name)
        return class_list.index(name)

    def save(self, target_file: str, class_list: Optional[List[str]] = None) -> bool:
        if not self.box_list:
            return False
        names = list(class_list if class_list is not None else self.class_list)
        w = max(1, self.img_w)
        h = max(1, self.img_h)
        lines = []
        for box in self.box_list:
            cls_id = self._ensure_class(box['name'], names)
            coords = []
            for x, y in box['points']:
                coords.append(f'{x / w:.6f}')
                coords.append(f'{y / h:.6f}')
            lines.append(f'{cls_id} ' + ' '.join(coords))
        os.makedirs(os.path.dirname(os.path.abspath(target_file)) or '.', exist_ok=True)
        with open(target_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
            f.write('\n')
        self.class_list = names
        return True


def annotations_to_obb_txt(
    annotations: Sequence[Dict[str, Any]],
    img_w: int,
    img_h: int,
    class_list: Sequence[str],
    output_path: str,
) -> bool:
    """
    Write internal-style annotations to YOLO-OBB txt.
    Only entries with type=='obb' (or >=4 points tagged as obb) are written.
    """
    writer = YOLOObbWriter([img_h, img_w], class_list=list(class_list))
    wrote = False
    for ann in annotations:
        pts = _obb_points_from_ann(ann)
        if not pts:
            continue
        writer.add_obb(pts, ann.get('label', ''))
        wrote = True
    if wrote:
        return writer.save(output_path, class_list=list(class_list))
    return False


def _obb_points_from_ann(ann: Dict[str, Any]) -> Optional[List[Tuple[float, float]]]:
    """Extract 4 pixel corners from an annotation dict, or None if not OBB."""
    ann_type = (ann.get('type') or '').lower()
    points = ann.get('points') or []
    if ann_type == 'obb' and len(points) >= 4:
        return [(float(p[0]), float(p[1])) for p in points[:4]]
    return None


def export_yolo_obb_dataset(
    items: Sequence[Dict[str, Any]],
    output_dir: str,
    class_list: Sequence[str],
    split: str = 'train',
    copy_images: bool = True,
) -> str:
    """
    Export items into YOLO-OBB layout under output_dir/split/.

    Each item:
      {
        'image_path': str,
        'annotations': [ {label, points=[[x,y],...]}, ... ]  # 4 corners, pixels
      }
    """
    import shutil

    images_dir = os.path.join(output_dir, split, 'images')
    labels_dir = os.path.join(output_dir, split, 'labels')
    os.makedirs(images_dir, exist_ok=True)
    os.makedirs(labels_dir, exist_ok=True)

    for item in items:
        image_path = item['image_path']
        if not os.path.isfile(image_path):
            continue
        base = os.path.splitext(os.path.basename(image_path))[0]
        ext = os.path.splitext(image_path)[1]
        dst_img = os.path.join(images_dir, base + ext)
        if copy_images:
            shutil.copy2(image_path, dst_img)

        from PySide6.QtGui import QImage
        img = QImage(image_path)
        writer = YOLOObbWriter(
            [img.height(), img.width()],
            class_list=list(class_list),
        )
        for ann in item.get('annotations', []):
            pts = ann.get('points') or _obb_points_from_ann(ann)
            if not pts or len(pts) < 4:
                continue
            writer.add_obb(pts, ann.get('label', ''))
        writer.save(os.path.join(labels_dir, base + TXT_EXT), class_list=list(class_list))

    yaml_path = os.path.join(output_dir, 'data.yaml')
    train = 'train/images' if os.path.isdir(os.path.join(output_dir, 'train', 'images')) else f'{split}/images'
    val = 'valid/images' if os.path.isdir(os.path.join(output_dir, 'valid', 'images')) else (
        'val/images' if os.path.isdir(os.path.join(output_dir, 'val', 'images')) else train
    )
    test = 'test/images' if os.path.isdir(os.path.join(output_dir, 'test', 'images')) else None
    write_data_yaml(
        yaml_path,
        names=class_list,
        train=train,
        val=val,
        test=test,
    )
    return yaml_path
